// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asqvdyozoddcljfyzzjf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzcXZkeW96b2RkY2xqZnl6empmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyMDUxMDQsImV4cCI6MjA1NDc4MTEwNH0.u0txk4rFSBuL4I_qEnW6MMY5IAPrGtC7U9NhkL-Ob0M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);